### ISSUE TITLE
Maps do not work

### ISSUE THREAD

**Issue by zoe12345** [pytrainer/pytrainer#103]
Although these packages are installed  (in archlinux) :
python2-gobject (3.26.1)  [Python2 Bindings for GLib/GObject/GIO/GTK+]
python2-gobject2 (2.28.6)  [Python2 bindings for GObject2]
webkitgtk  (2.4.11)  [Legacy Web content engine for GTK+ 3]
pywebkitgtk   (1.1.8)  [Python2 bindings to the WebKit GTK+ port]
webkit2gtk  (2.18.3)  [GTK+ Web content engine library]
webkitgtk2  (2.4.11)  [Legacy Web content engine for GTK+ 2]
python-webkit-server  (1.0)  [a Webkit-based, headless web client]
python2-webkit-server  (1.0)  [a Webkit-based, headless web client]

in the maps tab, I get message «Webkit not found, map functionality not available» (both Open Street Map and Google)

In 1.10.version of pytrainer, it used to work. What is wrong ?

**Comment by viiru-** [comment]
Can you test with commit 3e34394cf5803bcd9adfc678480f893808a08b26 applied?

I no longer have access to a system that has python-webkit, and apparently introduced at least one bug while making it optional.

**Comment by viiru-** [comment]
This is fixed by commit 3e34394cf580.
