### ISSUE TITLE
Startup fails with ImportError

### ISSUE THREAD

**Issue by cmcx** [pytrainer/pytrainer#114]
Pytrainer startup fails, message when starting from commandline reads:

~~~
`user@debian:~$ pytrainer
running pytrainer from egg installation
data_path: /usr/share/pytrainer/
gettext_path: /usr/share/locale
site_path: /usr/lib/python2.7/site-packages
Gtk-Message: Failed to load module "atk-bridge"
Traceback (most recent call last):
  File "/usr/bin/pytr", line 97, in <module>
    main()
  File "/usr/bin/pytr", line 93, in main
    from pytrainer.main import pyTrainer
  File "/usr/lib/python2.7/dist-packages/pytrainer/main.py", line 40, in <module>
    from gui.windowmain import Main
  File "/usr/lib/python2.7/dist-packages/pytrainer/gui/windowmain.py", line 38, in <module>
    from pytrainer.recordgraph import RecordGraph
  File "/usr/lib/python2.7/dist-packages/pytrainer/recordgraph.py", line 20, in <module>
    from gui.drawArea import DrawArea
  File "/usr/lib/python2.7/dist-packages/pytrainer/gui/drawArea.py", line 22, in <module>
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvasGTK
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import (
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 35, in <module>
    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
ImportError: No module named _backend_gdk`
~~~
Python version: 2.7.14+
matplotlib version: 2.1.1
pytrainer version: 1.11

**Comment by viiru-** [comment]
This seems to be caused by matplotlib not having GTK 2 support compiled in, please see https://github.com/matplotlib/matplotlib/issues/8441/ for more details.

**Comment by cmcx** [comment]
Okay, I understand the problem; my matplotlib-package is missing the GTK 2 support. I am using Debian Sid, GTK 2 support is deprecated in Debian, and so the package maintainer for matplotlib won't include GTK 2 support. I guess this means that GTK 2 support will soon be missing in other Debian based distributions, too.
Installing matplotlib via pip won't solve the problem, because GTK 2 support would be missing too. (via [this answer](https://github.com/matplotlib/matplotlib/issues/8441#issuecomment-292483849) to the matplotlib problem.
The only possibility seems to be compiling matplotlib from source including GTK2 support. 

Is there any chance that pytrainer will work with GTK 3 in the future?

**Comment by viiru-** [comment]
I'm using Debian Sid as well, but hadn't tested pytrainer since the latest update to matplotlib which removed this.

There is a plan to port pytrainer to GTK 3, and I did complete the first step of that plan for version 1.11.0 (converting from gtk.glade to gtkbuilder). I haven't so far managed to successfully run pytrainer with GTK 3, but I do hope to have the time to continue this work at some point.
