### ISSUE TITLE
`laptrigger VARCHAR(9)` is too short

### ISSUE THREAD

**Issue by a-mair** [pytrainer/pytrainer#143]
`laptrigger VARCHAR(9)` is too short. My laps table holds the values time, manual and laptrigger. "laptrigger" has 10 characters.

It doesn't harm in sqlite as it uses TEXT  here, but it should be fixed while you clean the database schema.

**Comment by a-mair** [comment]
I'm pretty sure that the content of this has been filled by pytrainer. So why did it store "laptrigger"?

**Comment by viiru-** [comment]
Andreas <notifications@github.com> writes:

> I'm pretty sure that the content of this has been filled by
> pytrainer. So why did it store "laptrigger"?

Because that is what the file you imported had in that field. It doesn't
check, it just stores whatever the imported file has exactly as-is (but
only really supports certain specific values).

-- 
Arto Jantunen
