### ISSUE TITLE
python3 problem: ModuleNotFoundError: No module named 'urlparse' 

### ISSUE THREAD

**Issue by heiderich** [pytrainer/pytrainer#189]
According to the release comment for https://github.com/pytrainer/pytrainer/releases/tag/v2.0.0rc1 pytrainer "has preliminary support for running under Python version 3". I tried installing pytrainer with python3 using `sudo python3 setup.py install`. However I cannot start it as the module `urlparse` is not found. According to https://docs.python.org/2/library/urlparse.html the module `urlparse` was renamed to `urllib.parse`.

**Comment by viiru-** [comment]
Can you test if this commit https://github.com/viiru-/pytrainer/commit/d2e321930dda829904eed59f33f7d74455ef5fac fixes the problem for you?

**Comment by heiderich** [comment]
Yes, it seems to fix the problem for me. Thank you!

**Comment by viiru-** [comment]
@heiderich Thanks for testing, the fix has been merged.
