### ISSUE TITLE
ValueError: Invalid date supplied: day is before 1st of month.

### ISSUE THREAD

**Issue by heiderich** [pytrainer/pytrainer#194]
I am getting the above mentioned error when I start pytrainer today (May 1, 2019) (master branch, i.e. commit e3e058e188256545c2a463a7b8077a9282673077).
It is raised in https://github.com/pytrainer/pytrainer/blob/e3e058e188256545c2a463a7b8077a9282673077/pytrainer/lib/date.py#L98-L99.

I think this is a bug introduced in b0111227b8eb31f3cedd74964c01756131a39b3d. Apart from fixing it, I would suggest
1) to document why this "hack for the gtk calendar widget" is necessary in the first place and
2) add unit tests for this function including border line cases.

**Comment by eetiez** [comment]
I had the same issue today. It is only due to the while loop in the getDate function in pytrainer/lib/date.py which doesn't take into account the case where day=1. As a result, the loop doesn't start and the exception is raised.

I've just made a PR to fix this little bug.

**Comment by heiderich** [comment]
Thanks @eetiez. This fixes the problem.

However I wonder why the `Selected day might be larger than current month's number of days` and what this function is supposed to return then. Therefore I think some unit tests could be beneficial here.

**Comment by viiru-** [comment]
This was fixed in PR #195
