### ISSUE TITLE
Version was not bumped

### ISSUE THREAD

**Issue by jtojnar** [pytrainer/pytrainer#201]
The title bar in 2.0.0 still shows rc1 because the following file was not updated:

https://github.com/pytrainer/pytrainer/blob/v2.0.0/pytrainer/__init__.py#L2

**Comment by viiru-** [comment]
Bah. I knew I forgot something. Thanks for the note.

**Comment by privong** [comment]
I think this was addressed for 2.0.1, but was not updated for 2.0.2?

**Comment by viiru-** [comment]
Indeed, I forgot to do this yet again.

**Comment by privong** [comment]
I think that this can be closed with the 2.1.0 release.
