### ISSUE TITLE
No OSM-Map & CSV-Export zero records

### ISSUE THREAD

**Issue by p-val** [pytrainer/pytrainer#206]
OS LEAP 15.1 and 2.0.0rc1
Two issues:
1. No OSM-map showing: **ImportError: No module named html**.
2. No CSV output created, no error message here.
[pytrainer_map_error.txt](https://github.com/pytrainer/pytrainer/files/3422005/pytrainer_map_error.txt)

Anything I can do to fix it?
tnx Peter

**Comment by avtobiff** [comment]
The `html` module was introduced in Python 3.
Can you try with Python 3 and see if that works?

It seems only `html.escape(data)` is used which is
equivalent to `cgi.escape(data, quote=true)`, which is
present in Python 2, but was deprecated in
Python 3.2 in favour of html.
