### ISSUE TITLE
Language translation wrong

### ISSUE THREAD

**Issue by ivel42** [pytrainer/pytrainer#212]
French instead of German
since commit https://github.com/pytrainer/pytrainer/commit/d9a21caa86b3736962b434a7ee382548a3856784

**Comment by a-mair** [comment]
Hi!

I had the same problem. Someone replaced the German translation by the French one.

I've taken the previous .po file and updated it, see attachment. Simply replace the false pytrainer.mo file by the attached one and pytrainer speaks German again. On my system the file is installed at /usr/share/locale/de/LC_MESSAGES

Some messages still aren't translated. If you find translation errors, please tell me.

Best regards,
Andreas
[de.zip](https://github.com/pytrainer/pytrainer/files/4464856/de.zip)
