### ISSUE TITLE
GPX import fails

### ISSUE THREAD

**Issue by esthet1cs** [pytrainer/pytrainer#62]
When trying to import a GPX-file (made with OsmAnd~ on my phone) into pytrainer, it produces an error (unknown file type). 
I'm using pytrainer 1.10.1-dev (which is the version in Debian sid)
The GPX-file is based on the topographix-schema (see below).
From the log it seems that pytrainer doesn't even try to import the file as a GPX-file, it only checks all the other formats, mostly garmin.
Importing FIT-files from my Garmin Forerunner 110 works flawless.

The log with the import window part is here: http://dock.in-berlin.de/paste/pytrainer.log

I have tried to convert the gpx file to the garmin training center format with gpsbabel. When importing that, pytrainer recognizes the format and lists the file in the uper part of the import window, but the Import-field is greyed out so I am not able to do the import.

I'm sure I'm doing something wrong, but I can't figure out what that is. Or ist pytrainer just not supporting this particular GPX-format?

This is the header and the first two segments of my GPX-file:

`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd~" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <trk>
    <trkseg>
      <trkpt lat="48.7728162" lon="9.2281778">
        <ele>424.0</ele>
        <time>2017-02-12T16:14:06Z</time>
        <hdop>30.0</hdop>
      </trkpt>
      <trkpt lat="48.7728933" lon="9.2280922">
        <ele>428.0</ele>
        <time>2017-02-12T16:14:12Z</time>
        <hdop>7.0</hdop>
      </trkpt>`

**Comment by MeisterP** [comment]
Same issue here with pytrainer version v1.11.0 and gpx files generated by the current release of OsmAnd~

**Comment by steckerhalter** [comment]
The gpx test fails here: https://github.com/pytrainer/pytrainer/blob/master/imports/file_gpxplus.py#L56

As a workaround I tried to ignore the test result and force the import. It worked allright. It seems to be an issue with the file test and not the OsmAnd GPX.

**Comment by MeisterP** [comment]
https://github.com/osmandapp/Osmand/issues/1326

> GPX v1.1 files generated by Osmand are invalid due to speed (in trkpt/extensions) belonging to the default/gpx namespace. GPX v1.1 schema requires that extensions belong to a "other" namespace.

**Comment by avtobiff** [comment]
Since this is an issue with OsmAnd~ and not pytrainer this can be closed.
